services:
  - type: web
    name: task-perfomance-optimizer
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health.php
    envVars:
      - key: DATABASE_URL
        sync: false
